### ISSUE TITLE
Run this script whenever the simulator is launched?

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/Nine41#1]
Not sure how difficult this would be.

😄 [From Dave](https://iosdevweekly.com/issues/424#tools):

> What I really want is for every simulator to start up every time with a perfect status bar. 

---

See `NSWorkspace.runningApplications`: 
https://developer.apple.com/documentation/appkit/nsworkspace/1534059-runningapplications

> use key-value observing to be notified of changes to this array property

**Comment by fotiDim** [comment]
A dirt simple way to do it is to put the script in a loop like so:

```
while sleep 1; 
do ./nine41.swift;
done
```

**Comment by jessesquires** [comment]
this can now be accomplish via SPM and Xcode

see:
https://www.jessesquires.com/blog/2020/04/13/fully-automating-perfect-status-bar-overrides-for-ios-simulators/
