### ISSUE TITLE
Show "9:41" in other timezones

### ISSUE THREAD

**Issue by aoenth** [jessesquires/Nine41#10]
The resulting time of "9:41" on iPhone simulators is shown in Pacific Time Zone. As a developer who wants to take screenshots in Eastern Time Zone, it shows 12:41. As a temporary solution I had to manually subtract `3 * 3600` from the hard-coded time in `main.swift`.

**Comment by jessesquires** [comment]
Thanks @aoenth !

This was also reported here: https://github.com/jessesquires/jessesquires.com/issues/112

I'd welcome a pull request if you want to take a stab at fixing this. 😄

**Comment by hiworld75018** [comment]
To build date/time from local time zone, you may change line 56 to :

```
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
dateFormatter.timeZone = TimeZone.current
dateFormatter.locale = Locale.current
let date = dateFormatter.date(from: "2007-01-09T09:41:00")!
```

**Comment by aoenth** [comment]
> Thanks @aoenth !
> 
> This was also reported here: [jessesquires/jessesquires.com#112](https://github.com/jessesquires/jessesquires.com/issues/112)
> 
> I'd welcome a pull request if you want to take a stab at fixing this. 😄

Hello @jessesquires,

Using the approach suggested by @hiworld75018, I have created a commit on a separate, local branch. Please grant me push access so I can create a pull request. Thank you!

**Comment by jessesquires** [comment]
Thanks @aoenth 💯 

You should be able to fork the repo, and then [submit a pull request](https://github.com/jessesquires/Nine41/compare) without push access. 😄
