### ISSUE TITLE
self.waitUntilExit() hangs

### ISSUE THREAD

**Issue by BMinas** [jessesquires/Nine41#11]
Thank you so much for giving us this - really useful!
Most of the time (for me) the script hangs on `self.waitUntilExit()` .  I'm running macOS 10.15.4 (19E287) and Xcode Version 11.4.1 (11E503a).  I moved the `let data = pipe.fileHandleForReading.readDataToEndOfFile()` to just before the waitUntilExit() and everything seems to work just fine.  Isn't this the prefered order?

**Comment by jessesquires** [comment]
Thanks @BMinas ! 🌈 

Let me look into this.

**Comment by jessesquires** [comment]
Seems to still work as expected after moving that line. Will change.
